export const ActionTypes = {
    SET_USER: 'SET_USER',
    SET_PHOTO: 'SET_PHOTO',
    SET_PROFILE: 'SET_PROFILE',
    CREATE_COURSE: 'CREATE_COURSE',
    GET_ALL_MYCOURSES: 'GET_ALL_MYCOURSES',
    SET_COURSE: 'SET_COURSE',
    SET_COURSE_GOALS: 'SET_COURSE_GOALS',
    SET_COURSE_DESCRIPTION: 'SET_COURSE_DESCRIPTION',
    SET_COURSE_PRICE: 'SET_COURSE_PRICE',
    SET_COURSE_PREVIEW_VIDEO: 'SET_COURSE_PREVIEW_VIDEO',
    SET_COURSE_LECTURES: 'SET_COURSE_LECTURES',
    ADD_LECTURE: 'ADD_LECTURE',
    DELETE_LECTURE: 'DELETE_LECTURE',
    SET_LECTURE_VIDEO: 'SET_LECTURE_VIDEO',
    SET_LECTURE_NAME: 'SET_LECTURE_NAME',
    SET_LECTURE_PREVIEW: 'SET_LECTURE_PREVIEW',
    PUBLISH_COURSE: 'PUBLISH_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    CHANGE_WISHLIST: 'CHANGE_WISHLIST',
    TAKE_COURSE: 'TAKE_COURSE',
    MARK_ALL_AS_READ: 'MARK_ALL_AS_READ',
    MARK_READ: 'MARK_READ',
    DEPOSIT_FUNDS: 'DEPOSIT_FUNDS',
    WITH_DRAW: 'WITH_DRAW',
    SET_PAYPALID: 'SET_PAYPALID',

    SHOW_MODAL: 'SHOW_MODAL',
    SET_GENRES: 'SET_GENRES',
    SET_GETMYCOURSES: 'SET_GETMYCOURSES',

    ADD_VIEW_COURSE: 'ADD_VIEW_COURSE'


}